# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_file_output_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='attrList',
        ),
        migrations.RemoveField(
            model_name='file',
            name='desc',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='data/'),
        ),
    ]
