# Generated by Django 2.0.1 on 2018-02-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180210_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='lastId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
