# Generated by Django 2.0.1 on 2018-02-15 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_responses_lastid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='username',
        ),
        migrations.AddField(
            model_name='responses',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
