# Generated by Django 2.0.1 on 2018-02-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180215_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='gotoId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
